PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/79589eca1a487f3d851ee937b508784831bf0df1

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/7fffab1610d2ea08a95383febd0579e0037b6b51) in current PX4/master (c5eefc6b2eed1741d12bec20bbe3aef6d38da3c6)
https://github.com/PX4/NuttX/compare/7fffab1610d2ea08a95383febd0579e0037b6b51...79589eca1a487f3d851ee937b508784831bf0df1

79589eca1a (HEAD, origin/master) cxd56: replace Sony return values
ecc4939453 cxd56: fix volume setting and improve volume range
36e756a915 cxd56: add support for pause and resume
7a83177419 cxd56: disable unused audio effects
d9d720b296 audio: nxstyle fixes for core and drivers
76c47f6b21 libc: audio: nxstyle fixes
fc8522cc97 tools/testbuild.sh: check status after make distclean
c2162365fc arch/arm/src/stm32h7/stm32_pwm: nxstyle fixes
d89b9102cc arch/arm/src/stm32h7/stm32_pwm: fix PWM_DUMP_REGS macro
655bb2e391 arch/arm/src/stm32/stm32_pwm: fix PWM_DUMP_REGS macro

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/989988fa7203ab5e5d26b140c8a43ddeb41d578e

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (c5eefc6b2eed1741d12bec20bbe3aef6d38da3c6)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...989988fa7203ab5e5d26b140c8a43ddeb41d578e

989988fa (HEAD -> master, origin/master) build.yml: Remove -G from cibuild.sh command line
f18b283e nshlib: add printf command to README.TXT
63288eb8 fix apps/include/graphics/nxwidgets/cwidgetcontrol.hxx:550:20: error: ‘m_xyinput’ was not declared in this scope
68ed2a2a build.yaml: Change arm-11 to arm-12
0c84e22a example: Remove all APPNAME from Makefile
4431d770 .gitignore: Add more entries found during prcheck testing
a82d74b8 nshlib: Call BOARDIOC_FINALINIT in nsh_telnetstart if CONFIG_NSH_CONSOLE not define
b1b45de3 Revert "nshlib: Move BOARDIOC_FINALINIT into nsh_initscript"
650b58d6 nshlib: Fix nxstyle warning
de8a56d1 nshlib: Split shell functionality from nsh to sh